# Generated by Django 3.0 on 2021-07-10 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import songs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_filename', models.CharField(max_length=200)),
                ('song_title', models.CharField(max_length=200, null=True)),
                ('song_album', models.CharField(max_length=200, null=True)),
                ('song_artist', models.CharField(max_length=200, null=True)),
                ('song_genre', models.CharField(max_length=200, null=True)),
                ('song_artwork', models.ImageField(null=True, upload_to=songs.models.user_directory_image_path)),
                ('music', models.FileField(upload_to=songs.models.user_directory_path)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
