# Generated by Django 3.0 on 2021-07-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_artwork',
            new_name='artwork',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_filename',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
    ]
