# Generated by Django 3.0 on 2021-07-10 13:58

from django.db import migrations, models
import songs.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20210710_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='posted_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_author',
        ),
        migrations.AddField(
            model_name='song',
            name='song_album',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='song_artwork',
            field=models.ImageField(null=True, upload_to=songs.models.user_directory_image_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_artist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_genre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
